const express = require('express');
const router = express.Router();
const jwt = require('jsonwebtoken');
const User = require('../models/User');
const bcrypt = require('bcryptjs');
const Ticket = require('../models/Ticket');
const NFT = require('../models/NFT');

// ========================
// ADMIN AUTH MIDDLEWARE
// ========================
const adminAuth = async (req, res, next) => {
  try {
    // Get token from header
    const authHeader = req.header('Authorization');
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ error: 'No token provided' });
    }
    
    const token = authHeader.replace('Bearer ', '');
    
    // Verify token
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    
    // Find user
    const user = await User.findById(decoded.userId);
    if (!user) {
      return res.status(401).json({ error: 'User not found' });
    }
    
    // Check if admin
    if (!user.isAdmin) {
      return res.status(403).json({ error: 'Admin access required' });
    }
    
    // Attach user to request
    req.user = user;
    next();
    
  } catch (error) {
    console.error('Admin auth error:', error.message);
    
    if (error.name === 'JsonWebTokenError') {
      return res.status(401).json({ error: 'Invalid token' });
    }
    
    if (error.name === 'TokenExpiredError') {
      return res.status(401).json({ error: 'Token expired' });
    }
    
    res.status(500).json({ error: 'Authentication failed' });
  }
};

// Authentication middleware
const authMiddleware = (req, res, next) => {
    const authHeader = req.header('Authorization');
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        return res.status(401).json({ error: 'Not authenticated' });
    }
    const token = authHeader.replace('Bearer ', '');
    try {
        const decoded = jwt.verify(token, process.env.JWT_SECRET);
        req.userId = decoded.userId;
        next();
    } catch (err) {
        res.status(401).json({ error: 'Invalid token' });
    }
};

// ========================
// REGISTER USER (UPDATED with wallet address)
// ========================
router.post('/register', async (req, res) => {
  try {
    const { email, password, fullName } = req.body;

    // Check if user exists
    const existingUser = await User.findOne({ email: email.toLowerCase().trim() });
    if (existingUser) {
      return res.status(400).json({ error: 'Email already exists' });
    }

    // Create new user (wallet address will be auto-generated by pre-save hook)
    const user = new User({
      email: email.toLowerCase().trim(),
      password: password,
      fullName: fullName || '',
      balance: 0,
      ethBalance: 0,
      wethBalance: 0,
      nftCount: 0
    });

    await user.save();

    // Generate token
    const token = jwt.sign(
      { userId: user._id, email: user.email },
      process.env.JWT_SECRET,
      { expiresIn: '7d' }
    );

    // Return user data WITH wallet address
    res.status(201).json({
      success: true,
      message: 'Registration successful',
      user: {
        _id: user._id,
        email: user.email,
        fullName: user.fullName,
        systemWalletAddress: user.systemWalletAddress,
        balance: user.balance,
        ethBalance: user.ethBalance,
        wethBalance: user.wethBalance,
        isAdmin: user.isAdmin
      },
      token
    });

  } catch (error) {
    console.error('Registration error:', error);
    res.status(500).json({ 
      error: 'Registration failed',
      details: error.message 
    });
  }
});

// ========================
// LOGIN USER (UPDATED with wallet address)
// ========================
router.post('/login', async (req, res) => {
  try {
    console.log('🔍 Starting login for:', req.body.email);
    
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({ error: 'Email and password are required' });
    }

    console.log('🔍 Looking for user...');
    const user = await User
      .findOne({ email: email.toLowerCase().trim() })
      .select('+password');

    console.log('🔍 User found:', user ? 'Yes' : 'No');
    
    if (!user) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    console.log('🔍 Comparing password...');
    const isPasswordValid = await user.comparePassword(password);
    console.log('🔍 Password valid:', isPasswordValid);
    
    if (!isPasswordValid) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    console.log('🔍 Updating last login...');
    await User.updateOne(
      { _id: user._id },
      { $set: { lastLogin: new Date() } }
    );

    console.log('🔍 Creating token...');
    const token = jwt.sign(
      { userId: user._id, email: user.email },
      process.env.JWT_SECRET,
      { expiresIn: '7d' }
    );

    console.log('✅ Login successful');
    res.json({
      success: true,
      message: 'Login successful',
      user: {
        _id: user._id,
        email: user.email,
        fullName: user.fullName,
        systemWalletAddress: user.systemWalletAddress,
        balance: user.balance,
        ethBalance: user.ethBalance,
        wethBalance: user.wethBalance,
        isAdmin: user.isAdmin,
        lastLogin: new Date()
      },
      token
    });

  } catch (error) {
    console.error('❌ Login error:', error);
    res.status(500).json({ 
      error: 'Login failed',
      details: error.message 
    });
  }
});

// ========================
// REFRESH TOKEN (UPDATED with wallet address)
// ========================
router.post('/auth/refresh', async (req, res) => {
  try {
    const { token } = req.body;
    
    if (!token) {
      return res.status(400).json({ error: 'Token required' });
    }
    
    // Verify old token
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    
    // Find user
    const user = await User.findById(decoded.userId);
    if (!user) {
      return res.status(401).json({ error: 'User not found' });
    }
    
    // Create new token
    const newToken = jwt.sign(
      { userId: user._id, email: user.email },
      process.env.JWT_SECRET,
      { expiresIn: '7d' }
    );
    
    res.json({
      success: true,
      token: newToken,
      user: {
        _id: user._id,
        email: user.email,
        fullName: user.fullName,
        systemWalletAddress: user.systemWalletAddress,
        isAdmin: user.isAdmin
      }
    });
    
  } catch (error) {
    console.error('Token refresh error:', error.message);
    
    if (error.name === 'TokenExpiredError') {
      return res.status(401).json({ error: 'Token expired. Please login again.' });
    }
    
    if (error.name === 'JsonWebTokenError') {
      return res.status(401).json({ error: 'Invalid token' });
    }
    
    res.status(500).json({ error: 'Token refresh failed' });
  }
});

// ========================
// GET CURRENT USER (UPDATED with wallet address)
// ========================
router.get('/me', authMiddleware, async (req, res) => {
    try {
        const user = await User.findById(req.userId).select('-password');
        if (!user) {
            return res.status(404).json({ error: 'User not found' });
        }
        res.json({ 
          user: {
            _id: user._id,
            email: user.email,
            fullName: user.fullName,
            systemWalletAddress: user.systemWalletAddress,
            balance: user.balance,
            ethBalance: user.ethBalance,
            wethBalance: user.wethBalance,
            isAdmin: user.isAdmin,
            lastLogin: user.lastLogin,
            createdAt: user.createdAt
          } 
        });
    } catch (error) {
        res.status(401).json({ error: 'Please authenticate' });
    }
});

// ========================
// LOGOUT
// ========================
router.post('/logout', (req, res) => {
    res.json({ success: true, message: 'Logged out successfully' });
});

// ========================
// UPDATE USER PROFILE
// ========================
router.put('/profile', authMiddleware, async (req, res, next) => {
    try {
        const user = await User.findById(req.userId);
        if (!user) {
            return res.status(404).json({ error: 'User not found' });
        }

        const { fullName } = req.body;
        if (fullName !== undefined) user.fullName = fullName;

        await user.save();

        res.json({
            success: true,
            message: 'Profile updated',
            user: {
                _id: user._id,
                email: user.email,
                fullName: user.fullName,
                systemWalletAddress: user.systemWalletAddress,
                balance: user.balance,
                ethBalance: user.ethBalance,
                wethBalance: user.wethBalance,
                isAdmin: user.isAdmin
            }
        });
    } catch (error) {
        console.error('Profile update error:', error);
        res.status(500).json({ error: 'Profile update failed' });
    }
});

// ========================
// TEST ROUTE - REMOVE AFTER DEBUGGING
// ========================
router.post('/login-test', (req, res) => {
  console.log('🔍 Test login endpoint hit');
  console.log('🔍 Email received:', req.body.email);
  
  // Just return a fake success response
  res.json({
    success: true,
    message: 'Test login successful',
    user: {
      _id: 'test-admin-id-123',
      email: req.body.email || 'test@admin.com',
      fullName: 'Test Admin',
      systemWalletAddress: '0x' + '1'.repeat(40),
      balance: 1000,
      ethBalance: 10,
      wethBalance: 10,
      isAdmin: true,
      lastLogin: new Date()
    },
    token: 'fake-jwt-token-for-testing'
  });
});

// ========================
// SUPPORT TICKET ROUTES (USER)
// ========================

// Submit support ticket (user only)
router.post('/support/ticket', authMiddleware, async (req, res) => {
    try {
        console.log('🎫 Creating support ticket for user:', req.userId);
        
        const { 
            subject, 
            category, 
            description, 
            email, 
            transactionHash, 
            urgent 
        } = req.body;
        
        // Validate required fields
        if (!subject || !category || !description || !email) {
            return res.status(400).json({ 
                success: false,
                error: 'Missing required fields: subject, category, description, email' 
            });
        }
        
        // Get user info
        const user = await User.findById(req.userId);
        if (!user) {
            return res.status(404).json({ 
                success: false,
                error: 'User not found' 
            });
        }
        
        // Create ticket (ticketId will be auto-generated by model)
        const ticket = new Ticket({
            user: req.userId,
            subject,
            category,
            message: description,
            description,
            email: email || user.email,
            transactionHash: transactionHash || '',
            urgent: urgent || false,
            priority: urgent ? 'high' : 'medium',
            status: 'open'
        });
        
        await ticket.save();
        
        console.log('✅ Ticket created:', ticket.ticketId);
        
        res.status(201).json({
            success: true,
            message: 'Support ticket submitted successfully',
            ticket: {
                id: ticket._id,
                ticketId: ticket.ticketId,
                subject: ticket.subject,
                category: ticket.category,
                priority: ticket.priority,
                status: ticket.status,
                createdAt: ticket.createdAt
            }
        });
        
    } catch (error) {
        console.error('❌ Ticket creation error:', error);
        res.status(500).json({ 
            success: false,
            error: 'Failed to create support ticket',
            message: error.message 
        });
    }
});

// Get user's tickets
router.get('/support/tickets', authMiddleware, async (req, res) => {
    try {
        const tickets = await Ticket.find({ user: req.userId })
            .sort({ createdAt: -1 })
            .select('-__v');
        
        res.json({
            success: true,
            tickets,
            count: tickets.length
        });
    } catch (error) {
        console.error('Get tickets error:', error);
        res.status(500).json({ 
            success: false,
            error: 'Failed to fetch tickets' 
        });
    }
});

// Get specific ticket
router.get('/support/tickets/:ticketId', authMiddleware, async (req, res) => {
    try {
        const ticket = await Ticket.findOne({ 
            ticketId: req.params.ticketId,
            user: req.userId 
        });
        
        if (!ticket) {
            return res.status(404).json({ 
                success: false,
                error: 'Ticket not found' 
            });
        }
        
        res.json({
            success: true,
            ticket
        });
    } catch (error) {
        console.error('Get ticket error:', error);
        res.status(500).json({ 
            success: false,
            error: 'Failed to fetch ticket' 
        });
    }
});

// ========================
// ADMIN ROUTES
// ========================

// Admin Dashboard Stats
router.get('/admin/stats', adminAuth, async (req, res) => {
  try {
    console.log('🔍 Admin stats requested by:', req.user.email);
    
    // Get counts from database
    const totalUsers = await User.countDocuments();
    const totalNFTs = await NFT.countDocuments();
    
    // Count open tickets
    const openTickets = await Ticket.countDocuments({ status: 'open' });
    
    // Calculate total volume
    const volumeResult = await NFT.aggregate([
      {
        $group: {
          _id: null,
          totalVolume: { $sum: "$price" }
        }
      }
    ]);
    
    const totalVolume = volumeResult.length > 0 ? volumeResult[0].totalVolume : 0;
    
    res.json({
      success: true,
      stats: {
        totalUsers,
        totalNFTs,
        totalVolume: totalVolume.toFixed(2),
        openTickets
      }
    });
    
  } catch (error) {
    console.error('❌ Admin stats error:', error);
    res.status(500).json({ 
      error: 'Failed to get admin stats',
      details: error.message 
    });
  }
});

// ========================
// NEW: ADMIN DASHBOARD STATS
// ========================
router.get('/admin/dashboard', adminAuth, async (req, res) => {
  try {
    console.log('🔍 Admin dashboard stats requested by:', req.user.email);
    
    const totalNFTs = await NFT.countDocuments();
    const totalUsers = await User.countDocuments();
    const openTickets = await Ticket.countDocuments({ status: 'open' });
    
    // Calculate total volume
    const volumeResult = await NFT.aggregate([
      { $group: { _id: null, total: { $sum: "$price" } } }
    ]);
    const totalVolume = volumeResult.length > 0 ? volumeResult[0].total : 0;
    
    // Count featured and boosted NFTs
    const featuredNFTs = await NFT.countDocuments({ isFeatured: true });
    const boostedNFTs = await NFT.countDocuments({ isPromoted: true });
    
    res.json({
      success: true,
      stats: {
        totalNFTs,
        totalUsers,
        totalVolume,
        openTickets,
        featuredNFTs,
        boostedNFTs
      }
    });
    
  } catch (error) {
    console.error('❌ Admin dashboard error:', error);
    res.status(500).json({ 
      error: 'Failed to fetch dashboard stats',
      details: error.message 
    });
  }
});

// ========================
// NEW: GET ALL NFTS (ADMIN)
// ========================
router.get('/admin/nfts', adminAuth, async (req, res) => {
  try {
    console.log('🔍 Admin fetching all NFTs');
    
    const nfts = await NFT.find({})
      .populate('owner', 'email fullName')
      .sort({ createdAt: -1 });
    
    res.json({
      success: true,
      nfts: nfts.map(nft => ({
        _id: nft._id,
        tokenId: nft.tokenId,
        name: nft.name,
        collectionName: nft.collectionName,
        price: nft.price,
        image: nft.image,
        views: nft.views || 0,
        likes: nft.likes || 0,
        boostedViews: nft.boostedViews || 0,
        boostedLikes: nft.boostedLikes || 0,
        isFeatured: nft.isFeatured || false,
        isPromoted: nft.isPromoted || false,
        owner: nft.owner,
        createdAt: nft.createdAt
      }))
    });
    
  } catch (error) {
    console.error('❌ Admin NFTs error:', error);
    res.status(500).json({ 
      error: 'Failed to fetch NFTs',
      details: error.message 
    });
  }
});

// ========================
// NEW: CREATE NFT (ADMIN)
// ========================
router.post('/admin/nfts', adminAuth, async (req, res) => {
  try {
    const { 
      name, 
      collectionName, 
      price, 
      category, 
      image, 
      ownerEmail,
      views,
      likes,
      isFeatured 
    } = req.body;
    
    console.log('📝 Admin creating NFT:', name);
    
    // Find owner by email
    const owner = await User.findOne({ email: ownerEmail });
    if (!owner) {
      return res.status(404).json({ error: 'Owner not found' });
    }
    
    const tokenId = 'ADMIN' + Date.now().toString(36).toUpperCase();
    
    const nft = new NFT({
      name,
      collectionName: collectionName || 'Admin Collection',
      price,
      category: category || 'art',
      image,
      owner: owner._id,
      tokenId,
      isListed: true,
      views: views || 0,
      likes: likes || 0,
      isFeatured: isFeatured || false
    });
    
    await nft.save();
    
    // Update user's NFT count
    owner.nftCount = (owner.nftCount || 0) + 1;
    await owner.save();
    
    res.json({
      success: true,
      message: 'NFT created successfully',
      nft
    });
    
  } catch (error) {
    console.error('❌ Admin create NFT error:', error);
    res.status(500).json({ 
      error: 'Failed to create NFT',
      details: error.message 
    });
  }
});

// ========================
// NEW: BOOST NFT (ADMIN)
// ========================
router.post('/admin/nfts/:id/boost', adminAuth, async (req, res) => {
  try {
    const { type, amount } = req.body;
    const nft = await NFT.findById(req.params.id);
    
    if (!nft) {
      return res.status(404).json({ error: 'NFT not found' });
    }
    
    if (type === 'views') {
      nft.boostedViews = (nft.boostedViews || 0) + parseInt(amount);
      nft.isPromoted = true;
    } else if (type === 'likes') {
      nft.boostedLikes = (nft.boostedLikes || 0) + parseInt(amount);
      nft.isPromoted = true;
    } else {
      return res.status(400).json({ error: 'Invalid boost type' });
    }
    
    await nft.save();
    
    res.json({
      success: true,
      message: `Boosted ${type} by ${amount}`,
      nft
    });
    
  } catch (error) {
    console.error('Boost NFT error:', error);
    res.status(500).json({ error: 'Failed to boost NFT' });
  }
});

// ========================
// NEW: FEATURE/UNFEATURE NFT (ADMIN)
// ========================
router.post('/admin/nfts/:id/feature', adminAuth, async (req, res) => {
  try {
    const { featured } = req.body;
    const nft = await NFT.findById(req.params.id);
    
    if (!nft) {
      return res.status(404).json({ error: 'NFT not found' });
    }
    
    nft.isFeatured = featured;
    await nft.save();
    
    res.json({
      success: true,
      message: `NFT ${featured ? 'featured' : 'unfeatured'} successfully`,
      nft
    });
    
  } catch (error) {
    console.error('Feature NFT error:', error);
    res.status(500).json({ error: 'Failed to feature NFT' });
  }
});

// ========================
// NEW: ADMIN SEARCH USERS BY WALLET ADDRESS (PARTIAL)
// ========================
router.get('/admin/users/search', adminAuth, async (req, res) => {
  try {
    const { wallet } = req.query;
    
    if (!wallet || wallet.length < 3) {
      return res.status(400).json({ 
        success: false, 
        error: 'Wallet address must be at least 3 characters' 
      });
    }

    console.log(`🔍 Admin searching for wallet: ${wallet}`);

    const users = await User.find({
      systemWalletAddress: { $regex: wallet, $options: 'i' }
    })
    .select('-password')
    .sort({ createdAt: -1 })
    .limit(20);

    console.log(`✅ Found ${users.length} users matching wallet: ${wallet}`);

    res.json({
      success: true,
      count: users.length,
      users: users.map(user => ({
        _id: user._id,
        email: user.email,
        fullName: user.fullName,
        systemWalletAddress: user.systemWalletAddress,
        balance: user.balance,
        ethBalance: user.ethBalance,
        wethBalance: user.wethBalance,
        isAdmin: user.isAdmin,
        createdAt: user.createdAt,
        lastLogin: user.lastLogin
      }))
    });

  } catch (error) {
    console.error('❌ Admin search error:', error);
    res.status(500).json({ 
      success: false,
      error: 'Failed to search users',
      details: error.message 
    });
  }
});

// ========================
// NEW: ADMIN EXACT SEARCH BY WALLET ADDRESS
// ========================
router.get('/admin/users/exact-search', adminAuth, async (req, res) => {
  try {
    const { wallet } = req.query;
    
    if (!wallet) {
      return res.status(400).json({ 
        success: false, 
        error: 'Wallet address is required' 
      });
    }

    console.log(`🔍 Admin exact searching for wallet: ${wallet}`);

    const user = await User.findOne({ 
      systemWalletAddress: wallet 
    }).select('-password');

    if (!user) {
      return res.json({
        success: true,
        found: false,
        message: 'No user found with this wallet address'
      });
    }

    res.json({
      success: true,
      found: true,
      user: {
        _id: user._id,
        email: user.email,
        fullName: user.fullName,
        systemWalletAddress: user.systemWalletAddress,
        balance: user.balance,
        ethBalance: user.ethBalance,
        wethBalance: user.wethBalance,
        isAdmin: user.isAdmin,
        createdAt: user.createdAt,
        lastLogin: user.lastLogin
      }
    });

  } catch (error) {
    console.error('❌ Admin exact search error:', error);
    res.status(500).json({ 
      success: false,
      error: 'Failed to search user',
      details: error.message 
    });
  }
});

// ========================
// ADMIN USER MANAGEMENT
// ========================

// Get all users (admin only)
router.get('/admin/users', adminAuth, async (req, res) => {
  try {
    console.log('🔍 Admin fetching all users');
    
    const users = await User.find({})
      .select('-password')
      .sort({ createdAt: -1 });
    
    res.json({
      success: true,
      users: users.map(user => ({
        _id: user._id,
        email: user.email,
        fullName: user.fullName,
        systemWalletAddress: user.systemWalletAddress,
        balance: user.balance,
        ethBalance: user.ethBalance,
        wethBalance: user.wethBalance,
        isAdmin: user.isAdmin,
        createdAt: user.createdAt,
        lastLogin: user.lastLogin
      }))
    });
    
  } catch (error) {
    console.error('❌ Admin users error:', error);
    res.status(500).json({ 
      error: 'Failed to fetch users',
      details: error.message 
    });
  }
});

// Update user WETH balance (admin only)
router.put('/admin/users/:userId/balance', adminAuth, async (req, res) => {
  try {
    const { userId } = req.params;
    const { balance, wethBalance } = req.body;
    
    const newWethBalance = wethBalance !== undefined ? wethBalance : balance;
    
    console.log(`🔍 Admin updating user ${userId} WETH balance to ${newWethBalance}`);
    
    if (newWethBalance === undefined || newWethBalance < 0) {
      return res.status(400).json({ error: 'Valid WETH balance required' });
    }
    
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    user.wethBalance = parseFloat(newWethBalance);
    await user.save();
    
    res.json({
      success: true,
      message: 'WETH balance updated successfully',
      user: {
        _id: user._id,
        email: user.email,
        systemWalletAddress: user.systemWalletAddress,
        wethBalance: user.wethBalance
      }
    });
    
  } catch (error) {
    console.error('❌ Update WETH balance error:', error);
    res.status(500).json({ 
      error: 'Failed to update WETH balance',
      details: error.message 
    });
  }
});

// Update user ETH balance (admin only)
router.put('/admin/users/:userId/eth-balance', adminAuth, async (req, res) => {
  try {
    const { userId } = req.params;
    const { ethBalance } = req.body;
    
    console.log(`🔍 Admin updating user ${userId} ETH balance to ${ethBalance}`);
    
    if (ethBalance === undefined || ethBalance < 0) {
      return res.status(400).json({ error: 'Valid ETH balance required' });
    }
    
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    user.ethBalance = parseFloat(ethBalance);
    await user.save();
    
    res.json({
      success: true,
      message: 'ETH balance updated successfully',
      user: {
        _id: user._id,
        email: user.email,
        systemWalletAddress: user.systemWalletAddress,
        ethBalance: user.ethBalance
      }
    });
    
  } catch (error) {
    console.error('❌ Update ETH balance error:', error);
    res.status(500).json({ 
      error: 'Failed to update ETH balance',
      details: error.message 
    });
  }
});

// ========================
// ADMIN TICKET MANAGEMENT
// ========================

// Get all support tickets (admin only)
router.get('/admin/tickets', adminAuth, async (req, res) => {
  try {
    console.log('🔍 Admin fetching all tickets');
    
    const tickets = await Ticket.find({})
      .populate('user', 'email fullName systemWalletAddress')
      .sort({ createdAt: -1 });
    
    res.json({
      success: true,
      tickets: tickets.map(ticket => ({
        _id: ticket._id,
        ticketId: ticket.ticketId,
        userId: ticket.user?._id,
        userEmail: ticket.user?.email || 'Unknown',
        userName: ticket.user?.fullName || 'Unknown',
        userWallet: ticket.user?.systemWalletAddress || 'Unknown',
        message: ticket.message,
        status: ticket.status,
        createdAt: ticket.createdAt,
        resolvedAt: ticket.resolvedAt
      }))
    });
    
  } catch (error) {
    console.error('❌ Admin tickets error:', error);
    res.status(500).json({ 
      success: false,
      error: 'Failed to fetch tickets',
      details: error.message 
    });
  }
});

// Resolve a ticket (admin only)
router.put('/admin/tickets/:ticketId/resolve', adminAuth, async (req, res) => {
  try {
    const { ticketId } = req.params;
    
    console.log(`🔍 Admin resolving ticket ${ticketId}`);
    
    const ticket = await Ticket.findById(ticketId);
    if (!ticket) {
      return res.status(404).json({ 
        success: false,
        error: 'Ticket not found' 
      });
    }
    
    ticket.status = 'resolved';
    ticket.resolvedAt = new Date();
    await ticket.save();
    
    res.json({
      success: true,
      message: 'Ticket resolved successfully',
      ticket: {
        _id: ticket._id,
        status: ticket.status,
        resolvedAt: ticket.resolvedAt
      }
    });
    
  } catch (error) {
    console.error('❌ Resolve ticket error:', error);
    res.status(500).json({ 
      success: false,
      error: 'Failed to resolve ticket',
      details: error.message 
    });
  }
});

// Close a ticket (admin only)
router.put('/admin/tickets/:ticketId/close', adminAuth, async (req, res) => {
  try {
    const { ticketId } = req.params;
    
    console.log(`🔍 Admin closing ticket ${ticketId}`);
    
    const ticket = await Ticket.findById(ticketId);
    if (!ticket) {
      return res.status(404).json({ 
        success: false,
        error: 'Ticket not found' 
      });
    }
    
    ticket.status = 'closed';
    await ticket.save();
    
    res.json({
      success: true,
      message: 'Ticket closed successfully',
      ticket: {
        _id: ticket._id,
        status: ticket.status
      }
    });
    
  } catch (error) {
    console.error('❌ Close ticket error:', error);
    res.status(500).json({ 
      success: false,
      error: 'Failed to close ticket',
      details: error.message 
    });
  }
});

module.exports = router;